---
title: "Distributional Models for Adolescent Brain Development"
format: dashboard
server: shiny
theme: [theme/custom.scss]
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| warning: false
#| message: false
#| output: false
#| context: setup

# load all necessary packages
library(tidyverse)
library(gt)
library(DT)
library(janitor)
library(shiny)
library(knitr)
library(kableExtra)
library(scales)
library(extrafont)
library(gamlss)
library(gamlss.ggplots)
library(plotly)
library(latex2exp)
library(ggseg)
library(patchwork)
library(gtsummary)

# set theme for visualizations
theme_set(theme_minimal(base_size = 16, base_family = "Atkinson Hyperlegible"))
```

```{r}
#| label: area-labels
#| output: false
#| context: data
#| warning: false
#| message: false
#| cache: true

# labels for cortical surface area variables
# from ABCD data dictionary
area_labels <- read_csv(
  "~/Equitable Data Science REU/distributional-models/additional data/Area_Variable_Labels.csv"
  ) |>
  # clean labels
  mutate(var_label = str_replace(var_label, "Cortical area in mm\\^", ""),
         var_label = str_replace(var_label, "2 of APARC ROI ", ""),
         var_label = str_replace(var_label, "lh-", "Left Hemisphere "),
         var_label = str_replace(var_label, "rh-", "Right Hemisphere "),
         var_label = str_replace(var_label, "cortical area in mm\\^2", ""),
         var_label = str_replace(var_label, "Total ", ""),
         var_label = str_to_lower(var_label))# |>
  # arrange in alphabetical order
 # arrange(var_label)

# save area labels as vector
area_vars <- area_labels$var_label
```

```{r}
#| label: thickness-labels
#| output: false
#| context: data
#| warning: false
#| message: false
#| cache: false

thickness_labels <- read_csv(
  "~/Equitable Data Science REU/distributional-models/additional data/Thickness_Variable_Labels.csv"
  ) |>
  mutate(var_label = str_remove_all(var_label, "Cortical thickness in mm of APARC ROI"),
         var_label = str_replace(var_label, "lh-", "left Hemisphere "),
         var_label = str_replace(var_label, "rh-", "right Hemisphere "),
         var_label = str_remove_all(var_label, "Mean cortical thickness in mm for "),
         var_label = str_remove_all(var_label, "Mean cortical thickness in mm "))

# save thickness labels as vector
thick_vars <- thickness_labels$var_label
```



```{r}
#| label: load-and-prep-data
#| output: false
#| context: data
#| warning: false
#| message: false
#| cache: true

# specify ABCD data directory
data_dir <- 'C:/Users/queen/Box/ABCD Tabulated Data/5.1/core/'

# NOTE: must run entire code chunk
if(!is.null(data_dir)){
  setwd(data_dir)
}

# LOAD DATA
# Demographic variables and propensity weights
demog <- read.csv("abcd-general/abcd_p_demo.csv", na.strings = c("999", "777"))
# Age in months, Site ID (ABCD Study Design Variables), Family ID
study_covars <- read.csv("abcd-general/abcd_y_lt.csv")
# desikan atlas, cortical thickness
dat.mri = read.csv('imaging/mri_y_smr_thk_dsk.csv')
# desikan atlas, cortical surface area
dat.mri.area = read.csv('imaging/mri_y_smr_area_dsk.csv') #|>
  #select(src_subject_id, eventname, smri_area_cdk_total)
```

```{r}
#| label: clean-demographic-variables
#| context: data
#| cache: true

# basic cleaning for demographic variables
demog_clean <- demog |>
  # filter for events of interest
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1")) |>
  # select broad demographics
  select(src_subject_id, eventname, starts_with("demo_brthdat_v2"), demo_sex_v2,
         race_ethnicity) |>
  mutate(
    # clean age variable
    age = case_when(
      eventname == "baseline_year_1_arm_1" ~ trunc(demo_brthdat_v2),
      eventname %in% c(
        "2_year_follow_up_y_arm_1", "4_year_follow_up_y_arm_1"
        ) ~ trunc(demo_brthdat_v2_l)),
    # broad race/ethnicity categories
    # will disaggregate in final analysis
    race_ethnicity = case_match(
      race_ethnicity,
      1 ~ "White",
      2 ~ "Black",
      3 ~ "Hispanic",
      4 ~ "Asian",
      5 ~ "Other"
    ),
    # recode sex variable
    sex = factor(demo_sex_v2),
    sex = fct_recode(
      sex,
      "Male" = "1",
      "Female" = "2",
      "Intersex-Male" = "3"
    ))
```

```{r}
#| label: prep-data-for-modeling
#| context: data
#| cache: true

# create dataset for modeling
mri_data <- dat.mri |>
  full_join(dat.mri.area, by = join_by("eventname", "src_subject_id")) |>
  # join mri data to demographics
  right_join(demog_clean, by = join_by("eventname", "src_subject_id")) |>
  # join to study covariates
  left_join(study_covars, by = join_by("eventname", "src_subject_id")) |>
  # select variables of interest
  select(src_subject_id, eventname, age, sex, site_id_l, race_ethnicity,
         interview_age, contains("smri_thick"), contains("smri_area_cdk")) |>
  # remove irrelevant ages 
  filter(age < 16 & age > 8) |>
  mutate(interview_age = as.numeric(interview_age)) |>
  group_by(src_subject_id) |>
  drop_na(smri_thick_cdk_mean, smri_area_cdk_total) |>
  # fill repeated demographic values
  mutate(sex = first(na.omit(sex)),
         race_ethnicity = first(na.omit(race_ethnicity)),
         src_subject_id = factor(src_subject_id),
         site_id_l = factor(site_id_l),
         race_ethnicity = factor(race_ethnicity)) |>
  ungroup()

# dataset to be subsetted for models
brain_data <- mri_data |>
  # na.omit(mri_data) |>
  filter(sex != "Intersex-Male") |>
  mutate(sex = factor(sex))
```

```{r}
#| label: visualizations-for-poster
#| eval: false

library(patchwork)

area_density <- brain_data |> 
  filter(!is.na(sex) & !is.na(race_ethnicity) & sex != "Intersex-Male") |>
  mutate(race_ethnicity = if_else(race_ethnicity == "Other", "Not Listed", race_ethnicity)) |>
  ggplot(aes(x = smri_area_cdk_total)) +
  geom_density(aes(fill = sex), alpha = 0.5) +
  facet_wrap(~race_ethnicity, ncol = 1) +
  scale_x_continuous(label = label_comma()) +
  scale_fill_manual(values = c("steelblue1", "tomato1")) + 
  labs(title = NULL,
       x = TeX("Cortical Surface Area ($mm^2$)"),
       y = NULL,
       fill = "Sex") +
  theme_minimal(base_family = "Lato") +
  theme(axis.text.y = element_blank(),
        legend.position = "top")

thick_density <- brain_data |> 
  filter(!is.na(sex) & !is.na(race_ethnicity) & sex != "Intersex-Male") |>
  mutate(race_ethnicity = if_else(race_ethnicity == "Other", "Not Listed", race_ethnicity)) |>
  ggplot(aes(x = smri_thick_cdk_mean)) +
  geom_density(aes(fill = sex), alpha = 0.5, show.legend = FALSE) +
  facet_wrap(~race_ethnicity, ncol = 1) +
  scale_x_continuous(label = label_comma()) +
  scale_fill_manual(values = c("steelblue1", "tomato1")) + 
  labs(title = NULL,
       x = "Mean Cortical Thickness (mm)",
       y = NULL) +
  theme_minimal(base_family = "Lato") +
  theme(axis.text.y = element_blank())

area_density + thick_density

demog_brain_combos_area <- as.data.frame(demog_brain_combos_area)
index_1 <- which(demog_brain_combos_area$sex == "Female" & demog_brain_combos_area$race_ethnicity == "White" & demog_brain_combos_area$var_name == "smri_area_cdk_total")
index_2 <- which(demog_brain_combos_area$sex == "Male" & demog_brain_combos_area$race_ethnicity == "Black" & demog_brain_combos_area$var_name == "smri_area_cdk_total")
data_1 <- data_list[[index_1]]
data_2 <- data_list[[index_2]]
model_1 <- model_list[[index_1]]
model_2 <- model_list[[index_2]]

white_female_plot <- centiles_plot(
  model_1,
  data_1,
  substitute(interview_age),
  "smri_area_cdk_total",
  c(0.4, 2, 10, 25, 50, 75, 90, 98, 99.6),
  race = "White",
  sex = "Female"
)

black_male_plot <- centiles_plot(
  model_2,
  data_2,
  substitute(interview_age),
  "smri_area_cdk_total",
  c(0.4, 2, 10, 25, 50, 75, 90, 98, 99.6),
  race = "Black",
  sex = "Male"
)
white_female_plot + black_male_plot
```



```{r}
#| label: additional-prep-for-brain-plots
#| context: data
#| cache: true

brain_pictures <- brain_data |> 
  pivot_longer(cols = contains("smri_thick"), names_to = "phenotype") |> 
  #add hemisphere classification 
  mutate(hemisphere = case_when(
    grepl("lh", phenotype) ~ "left",
    grepl("rh", phenotype) ~ "right",
    .default = NA),
    #use forcats to collapse regions 
    region = factor(phenotype),
    region = fct_collapse(
      phenotype,
      "pericalcarine" = c("smri_thick_cdk_pericclh", "smri_thick_cdk_periccrh"),
      "caudal anterior cingulate" = c("smri_thick_cdk_cdacatelh", "smri_thick_cdk_cdacaterh"),
      "caudal middle frontal" = c("smri_thick_cdk_cdmdfrlh", "smri_thick_cdk_cdmdfrrh"),
      "cuneus" = c("smri_thick_cdk_cuneuslh", "smri_thick_cdk_cuneusrh"),
      "entorhinal" = c("smri_thick_cdk_ehinallh", "smri_thick_cdk_ehinalrh"),
      "fusiform" = c("smri_thick_cdk_fusiformlh", "smri_thick_cdk_fusiformrh"),
      "inferior parietal" = c("smri_thick_cdk_ifpllh", "smri_thick_cdk_ifplrh"),
      "isthmus cingulate" = c("smri_thick_cdk_ihcatelh", "smri_thick_cdk_ihcaterh"),
      "lateral occipital" = c("smri_thick_cdk_locclh", "smri_thick_cdk_loccrh"),
      "lateral orbitofrontal" = c("smri_thick_cdk_lobfrlh", "smri_thick_cdk_lobfrrh"),
      "lingual" = c("smri_thick_cdk_linguallh", "smri_thick_cdk_lingualrh"),
      "medial orbitofrontal" = c("smri_thick_cdk_mobfrlh", "smri_thick_cdk_mobfrrh"),
      "middle temporal" = c("smri_thick_cdk_mdtmlh", "smri_thick_cdk_mdtmrh"),
      "parahippocampal" = c("smri_thick_cdk_parahpallh", "smri_thick_cdk_parahpalrh"),
      "paracentral" = c("smri_thick_cdk_paracnlh", "smri_thick_cdk_paracnrh"),
      "pars opercularis" = c("smri_thick_cdk_parsopclh", "smri_thick_cdk_parsopcrh"),
      "pars orbitalis" = c("smri_thick_cdk_parsobislh", "smri_thick_cdk_parsobisrh"),
      "pars triangularis" = c("smri_thick_cdk_parstgrislh", "smri_thick_cdk_parstgrisrh"),
      "pericalcarine" = c("smri_thick_cdk_pericclh", "smri_thick_cdk_periccrh"),
      "postcentral" = c("smri_thick_cdk_postcnlh", "smri_thick_cdk_postcnrh"),
      "posterior cingulate" = c("smri_thick_cdk_ptcatelh", "smri_thick_cdk_ptcaterh"),
      "precentral" = c("smri_thick_cdk_precnlh", "smri_thick_cdk_precnrh"),
      "precuneus" = c("smri_thick_cdk_pclh", "smri_thick_cdk_pcrh"),
      "rostral anterior cingulate" = c("smri_thick_cdk_rracatelh", "smri_thick_cdk_rracaterh"),
      "rostral middle frontal" = c("smri_thick_cdk_rrmdfrlh", "smri_thick_cdk_rrmdfrrh"),
      "superior frontal" = c("smri_thick_cdk_sufrlh", "smri_thick_cdk_sufrrh"),
      "superior parietal" = c("smri_thick_cdk_supllh", "smri_thick_cdk_suplrh"),
      "superior temporal" = c("smri_thick_cdk_sutmlh", "smri_thick_cdk_sutmrh"),
      "supramarginal" = c("smri_thick_cdk_smlh", "smri_thick_cdk_smrh"),
      "frontal pole" = c("smri_thick_cdk_frpolelh", "smri_thick_cdk_frpolerh"),
      "temporal pole" = c("smri_thick_cdk_tmpolelh", "smri_thick_cdk_tmpolerh"),
      "transverse temporal" = c("smri_thick_cdk_trvtmlh", "smri_thick_cdk_trvtmrh"),
      "insula" = c("smri_thick_cdk_insulalh", "smri_thick_cdk_insularh"),
      "inferior temporal" = c("smri_thick_cdk_iftmlh", "smri_thick_cdk_iftmrh"),
      "bankssts" = c("smri_thick_cdk_banksstslh", "smri_thick_cdk_banksstsrh"),
      other_level = 'missing')) |>
  select(src_subject_id, eventname, age, sex, site_id_l, race_ethnicity,
         interview_age, phenotype, value, hemisphere, region) |>
  na.omit()
```

```{r}
#| label: find-demographic-combinations
#| context: data
#| cache: true

# find all combinations of race and sex
demog_combos <- brain_data |>
  mutate(race_ethnicity = as.character(race_ethnicity),
         sex = factor(sex)) |>
  expand(sex, race_ethnicity) |>
  na.omit()

# create vectors to add "All" race category
male_all <- c("Male", "All")
female_all <- c("Female", "All")

# add "All" category to combinations
demog_combos <- rbind(demog_combos, male_all, female_all)

# find y axis limits for area variables
limits_area <- brain_data |> pivot_longer(
  cols = starts_with("smri_area"),
  names_to = "var_name",
  values_to = "values"
) |>
  group_by(var_name) |>
  summarize(
    min_value = mean(values) - 3*sd(values),
    max_value = mean(values) + 3*sd(values)
  )

# find y axis limits for thickness variables
limits_thick <- brain_data |> pivot_longer(
  cols = starts_with("smri_thick"),
  names_to = "var_name",
  values_to = "values"
) |>
  group_by(var_name) |>
  summarize(
    min_value = mean(values) - 3*sd(values),
    max_value = mean(values) + 3*sd(values)
  )

# demographic combinations matrix for area variables
demog_brain_combos_area <- expand.grid(
  sex = demog_combos$sex,
  race_ethnicity = demog_combos$race_ethnicity,
  brain_location = area_vars) |>
  distinct() |>
  left_join(area_labels, by = join_by(brain_location == var_label)) |>
  left_join(limits_area, by = join_by(var_name)) |>
  mutate(sex = factor(sex),
         race_ethnicity = factor(race_ethnicity),
         brain_location = factor(brain_location),
         min_value = as.numeric(min_value),
         max_value = as.numeric(max_value)) |>
  as.matrix()

# demographic combinations matrix for thickness variables
demog_brain_combos_thick <- expand.grid(
  sex = demog_combos$sex,
  race_ethnicity = demog_combos$race_ethnicity,
  brain_location = thickness_labels$var_name) |>
  distinct() |>
  left_join(thickness_labels, by = join_by(brain_location == var_name)) |>
  left_join(limits_thick, by = join_by(brain_location == var_name)) |>
  mutate(sex = factor(sex),
         race_ethnicity = factor(race_ethnicity),
         brain_location = factor(brain_location),
         min_value = as.numeric(min_value),
         max_value = as.numeric(max_value)) |>
  select(sex, race_ethnicity, brain_location, var_label, min_value,
         max_value) |>
  as.matrix()
```

```{r}
#| label: subset-data-function
#| context: setup
#| output: false

# SUBSETS DATA BY FILTERING FOR UP TO 2 VARIABLES
# PREPS DATA FOR MODELING
# EX. SEX = "MALE" AND RACE = "BLACK"
subset_data <- function(
    # full dataset
    brain_data,
    # xvariable
    xcol,
    # yvariable
    ycol,
    # first variable to filter by
    filter_var1 = NULL,
    # value of first variable to filter for
    filter_val1 = NULL,
    # second variable to filter by
    filter_var2 = NULL,
    # value of second variable to filter for
    filter_val2 = NULL
) {
  
  # removes underrepresented sex and omits NA values
  brain_data <- brain_data |>
    filter(sex != "Intersex-Male") |>
    mutate(sex = factor(sex)) |>
    na.omit()
  
  if(filter_val2 == "All") {
    filter_var2 = NULL
    filter_val2 = NULL
  }
  
    # subset data
  if(!is.null(filter_var1) & !is.null(filter_val1) & is.null(filter_var2) & is.null(filter_var2)) {
    data_subset <- subset(
      brain_data, brain_data[[filter_var1]] == filter_val1)
  }
  if(!is.null(filter_var2) & !is.null(filter_var2)) {
    data_subset <- subset(
      brain_data, brain_data[[filter_var1]] == filter_val1 & brain_data[[filter_var2]] == filter_val2)
    
  }
  if(is.null(filter_var1) & is.null(filter_val1) & is.null(filter_var2) & is.null(filter_var2)) {
    data_subset <- brain_data
  }
  
  # creates xvar and yvar columns in dataset
  data_subset$xvar <- data_subset[[xcol]]
  data_subset$yvar <- data_subset[[ycol]]
  
  return(data_subset)
}
```

```{r}
#| label: model-cortical-area-function
#| context: setup
#| output: false

# Takes output of subset_data() function as argument
area_model <- function(data_subset) {
  
  # finds power transformation for gamlss model
  power <- gamlss::findPower(yvar, xvar, data = data_subset, k = 2)
  
  # build gamlss model for subsetted data
  model <- gamlss(
  yvar ~ pb(xvar^power) + gamlss::random(src_subject_id) + gamlss::random(site_id_l),
  sigma.formula = ~pb(xvar),
  tau.formula = ~xvar,
  nu.formula = ~xvar,
  family = BCPEo,
  data = data_subset
  )

  return(model)
}

```

```{r}
#| label: calculate-centiles-function
#| context: setup
#| output: false

# creates data frame of centiles for a given model object
# model_data *MUST* be the same data used to build model object
calculate_centiles <- function(
  # GAMLSS model object
  model,
  # data used to build model
  model_data,
  # x variable in model_data
  xcol,
  # y variable in model_data
  ycol,
  # centiles to calculate
  cent = c(97.5, 50, 2.5)
) {
  
xvar_ch <- deparse(xcol)
yvar_ch <- ycol
obj = model
x <- y <- NULL

xvar  <- get(xvar_ch, envir=as.environment(model_data))
fname <- obj$family[1]
qfun <- paste("q",fname,sep ="")
oxvar <- xvar[order(xvar)]
oyvar <- obj$y[order(xvar)]

lpar <- 4

ii <- 0
per <- rep(0, length(cent))
centile_matrix <- matrix(0, ncol = length(cent), nrow = dim(model_data)[1])
colnames(centile_matrix) <- cent

for(var in cent) {
  newcall <- call(qfun,var/100,
                  mu=fitted(obj,"mu")[order(xvar)],
                     sigma=fitted(obj,"sigma")[order(xvar)],
                     nu=fitted(obj,"nu")[order(xvar)],
                     tau=fitted(obj,"tau")[order(xvar)]) 
    ii <- ii + 1
    centile_matrix[,ii] <- eval(newcall)
}

#yvar_ch <- paste(obj$call$formula[[2]])

lc <- length(cent)
centile_data <- data.frame(
  centile = centile_matrix,
  x = oxvar,
  y = oyvar)

return(centile_data)
}
```

```{r}
#| label: plot-centiles-function
#| context: setup
#| output: false



# returns ggplot for given model and data used to create model
centiles_plot <- function(
    # gamlss model object
    model,
    # data used to create gamlss model
    model_data,
    # x variable in data
    xcol,
    # y variable in data
    ycol,
    cent = c(2.5, 50, 97.5),
    # whether to include points on plot in addition to centile curves
    points = TRUE,
    race = "",
    sex = "",
    ylims = c(125000, 250000),
    region = "Total Brain"
    ) {
  
  centile_data <- calculate_centiles(model, model_data, xcol, ycol, cent)
  lc <- length(cent)
  c_names <- colnames(centile_data)
  line.size = 1.5
  line.col = hcl.colors(lc, palette = "Dark 2")
  line.type = rep(1, length(cent))
  
  # initialize ggplot object
  gg <- ggplot(data = centile_data)
  
  if(points == TRUE) {
    gg <- gg + geom_point(aes(x = x, y = y),
             size = 1, alpha = 0.2, show.legend = FALSE, color = "gray")
  }
  for(i in 1:lc) {
    
    if(c_names[i] == "centile.50") {
      gg <- gg +
      geom_line(
        aes_string(x = "x", y = c_names[i]),
        color = line.col[i], linewidth = line.size)
    }
    
    else {
      gg <- gg +
      geom_line(
        aes_string(x = "x", y = c_names[i]),
        color = line.col[i], linetype = "dashed", linewidth = line.size)
    }
    
  }
  
  gg <- gg +
    scale_y_continuous(label = comma, limits = ylims) +
    scale_x_continuous(breaks = c(108,120,132,144, 156, 168,180,192),
                     labels = c(9,10,11,12,13,14,15,16)) +
    labs(x = "Age (Years)", y = TeX("Cortical Surface Area in $mm^2$"),
         title = paste(
           "Centiles for", region, "\nfor", race, sex, "Adolescents", sep = " "),
         subtitle = "Using Box-Cox Power Exponential Original Family")
    theme_minimal()  
  
  return(gg)
}
```

```{r}
#| label: download-models-area
#| eval: false

save(model_list, file = "area_model_list.RData")
```

```{r}
#| label: area-model-data
#| context: data
#| cache: true
#| cache-lazy: false

data_list <- list()

for(row in 1:nrow(demog_brain_combos_area)) {
  
  my_ycol <- demog_brain_combos_area[row,4]
  
  
  data_list[[row]] = subset_data(
    brain_data,
    xcol = "interview_age",
    ycol = my_ycol,
    filter_var1 = "sex",
    filter_val1 = demog_brain_combos_area[row, 1],
    filter_var2 = "race_ethnicity",
    filter_val2 = demog_brain_combos_area[row, 2])
}

```


```{r}
#| label: load-models-area
#| context: data
#| cache: false
#| cache-lazy: false

setwd("~/Equitable Data Science REU/distributional-models")
load("area_model_list.RData")
```

```{r}
#| label: build-models-area
#| context: data
#| output: false
#| message: false
#| warning: false
#| eval: false
#| cache-lazy: false
#| cache: false

# create models for each combination of sex and race
model_list <- list()
for(row in 1:nrow(demog_brain_combos_area)) {
  print(
    paste("FITTING MODEL", row, ":", demog_brain_combos_area[row,2],
          demog_brain_combos_area[row,1], demog_brain_combos_area[row,3]))
  model_list[[row]] = area_model(data_subset = data_list[[row]])
}
```

```{r}
#| label: build-models-thickness-function
#| context: data
#| eval: false
#| cache-lazy: false
#| cache: false

#make models 
thickness_model <- function(data_subset) {
  power <- gamlss::findPower(yvar, xvar, data = na.omit(data_subset), k = 2)
  # build gamlss model
  model <- gamlss(
  yvar ~ pb(xvar^power) + gamlss::random(src_subject_id) + gamlss::random(site_id_l),
  sigma.formula = ~pb(xvar),
  tau.formula = ~xvar,
  nu.formula = ~xvar,
  family = BCTo,
  data = na.omit(data_subset)
  )

  return(model)
}


summary(thick_model_list[[1]])
```

```{r}
#| label: thickness-model-data
#| context: data
#| eval: true
#| cache: false
#| cache-lazy: false

thick_data_list <- list()
for(row in 1:nrow(demog_brain_combos_thick)) {
  
  my_ycol <- demog_brain_combos_thick[row,3]
  
  thick_data_list[[row]] = subset_data(
    brain_data,
    xcol = "interview_age",
    ycol = my_ycol,
    filter_var1 = "sex",
    filter_val1 = demog_brain_combos_thick[row, 1],
    filter_var2 = "race_ethnicity",
    filter_val2 = demog_brain_combos_thick[row, 2])
}
```

```{r}
#| label: load-models-thickness
#| context: data
#| cache: false
#| cache-lazy: false
#| output: false

setwd("~/Equitable Data Science REU/distributional-models")
load("thick_model_list_updated.RData")
```

```{r}
#| label: build-models-thickness
#| eval: false

thick_model_list <- list()
for(row in 1:1) {
  print(
    paste("FITTING MODEL", row, ":", demog_brain_combos_thick[row,2],
          demog_brain_combos_thick[row,1], demog_brain_combos_thick[row,5]))
  thick_model_list[[row]] = thickness_model(data_subset = thick_data_list[[row]])
}

setwd("~/Equitable Data Science REU/distributional-models")
save(thick_model_list, file = "thick_model_list_updated.RData")
```

# Home

##  {.sidebar width="25%"}

**Project Background**

## Column

```{r}
#| label: abstract
#| title: "Abstract"
```

```{r}
#| label: modeling-appraoch
#| title: "Modeling Approach"

print("Hello World")
```


```{r}
#| label: table-1
#| title: "Table 1. Sample Demographics"
#| eval: false

distinct(brain_data, src_subject_id)

brain_data |>
  na.omit() |>
  select(eventname, race_ethnicity, sex) |>
  mutate(eventname = case_match(
    eventname,
    "baseline_year_1_arm_1" ~ "Baseline",
    "2_year_follow_up_y_arm_1" ~ "2-Year Follow Up",
    "4_year_follow_up_y_arm_1" ~ "4-Year Follow Up"
  ),
  eventname = factor(eventname),
  eventname = fct_relevel(eventname, c("Baseline", "2-Year Follow Up", "4-Year Follow Up" )),
  race_ethnicity = if_else(race_ethnicity == "Other", "Not Listed", race_ethnicity)) |>
  tbl_summary(
    by = eventname,
    label = list(
    #eventname ~ "Study timepoint",
    race_ethnicity ~ "Race",
    sex ~ "Sex"
    ),
    sort = list(everything() ~ "frequency")
  ) |>
  bold_labels() |>
  add_overall() |>
  modify_spanning_header(all_stat_cols() ~ "**Timepoint**") |>
  modify_header(all_stat_cols() ~ "**{level}**<br> N = {style_number({n})}") |>
as_gt() |>
  tab_header(md("**Table 1**. ABCD Sample Demographics, N = 22,633"), subtitle = NULL, preheader = NULL) |>
  tab_footnote(
  footnote = "Sample includes 22,633 total observations from 11,692 unique participants. At baseline, participants are primarily ages 9 and 10. Participants are primarily ages 11 and 12 at the 2-year follow-up timepoint and ages 13 and 14 at the 4-year follow-up timepoint.",
  location = cells_title()
  )

```

# Centile Estimation

Text here

## Column {width="50%"}

```{r}
#| title: "Input Individual Data to Determine Centile"
#| label: input-data-for-centiles

print("Hello World")

```

## Column {width="50%"}

```{r}
#| title: "Determine Centiles for Subpopulation"
#| label: subpop-centiles

print("Hello World")

```

# Cortical Thickness

## {.toolbar}

```{r}
#| label: thickness-global-input
#| title: "Select Options"
#| layout-nrow: 2
#| layout-ncol: 1

# select y variable
selectInput(
  "thickness_var",
  "Select area of brain to model cortical surface area: ",
  thickness_labels$var_label,
  selected = c("whole brain")
  )

# centile input boxes
checkboxGroupInput(
  "centiles_thickness",
  "Select Centiles to Include in Plot",
  c(0.4, 2, 2.5, 10, 25, 50, 75, 90, 97.5, 98, 99.6),
  selected = c(2.5, 50, 97.5),
  inline = TRUE
  )

```

## Row

```{r}
#| content: card-toolbar
#| label: thickness-plot-1-input

race_levels <- c(levels(brain_data$race_ethnicity), "All")

# select race
selectInput(
  "race3",
  "Race",
  choices = race_levels,
  multiple = FALSE,
  selected = "All"
)

# select sex
selectInput(
  "sex3",
  "Sex",
  choices = c("Male", "Female"),
  multiple = FALSE,
  selected = "Female"
)
```

```{r}
#| title: "Plot 1"
#| label: thickness-plot-1

plotOutput("thick_centile_plot_1")
```

```{r}
#| content: card-toolbar
#| label: thickness-plot-2-input

# select race
selectInput(
  "race4",
  "Race",
  choices = race_levels,
  multiple = FALSE,
  selected = "All"
)

# select sex
selectInput(
  "sex4",
  "Sex",
  choices = c("Male", "Female"),
  multiple = FALSE,
  selected = "Male"
)

```

```{r}
#| title: "Plot 2"
#| label: thickness-plot-2

plotOutput("thick_centile_plot_2")

```

```{r}
#| label: thickness-calculate-and-plot-centiles
#| context: server

output$thick_centile_plot_1 <- renderPlot({
  
  demog_brain_combos_thick <- as.data.frame(demog_brain_combos_thick)

  race3 <- input$race3[1]
  sex3 <- input$sex3[1]

  centiles_to_plot <- as.numeric(input$centiles_thickness)
  region_label <-  input$thickness_var[1]
  region_var <- thickness_labels$var_name[which(thickness_labels$var_label == region_label)]
  
  index <- which(demog_brain_combos_thick$sex == sex3 & demog_brain_combos_thick$race_ethnicity == race3 & demog_brain_combos_thick$var_label == region_label)

  demog_brain_combos_thick <- as.matrix(demog_brain_combos_thick)

  y_limits <- c(as.numeric(demog_brain_combos_thick[index, 5]),
                as.numeric(demog_brain_combos_thick[index, 6]))
  
  model_data <- thick_data_list[[index]]
  model_obj <- thick_model_list[[index]]
  
  centiles_plot(
    model_obj,
    model_data,
    xcol = substitute(interview_age),
    ycol = region_var,
    cent = centiles_to_plot,
    race = race3,
    sex = sex3,
    ylims = y_limits,
    region = region_label
  )
  
})

output$thick_centile_plot_2 <- renderPlot({
  
  demog_brain_combos_thick <- as.data.frame(demog_brain_combos_thick)

  race4 <- input$race4[1]
  sex4 <- input$sex4[1]

  centiles_to_plot <- as.numeric(input$centiles_thickness)
  region_label <-  input$thickness_var[1]
  region_var <- thickness_labels$var_name[which(thickness_labels$var_label == region_label)]
  
  index <- which(demog_brain_combos_thick$sex == sex4 & demog_brain_combos_thick$race_ethnicity == race4 & demog_brain_combos_thick$var_label == region_label)

  demog_brain_combos_thick <- as.matrix(demog_brain_combos_thick)

  y_limits <- c(as.numeric(demog_brain_combos_thick[index, 5]),
                as.numeric(demog_brain_combos_thick[index, 6]))
  
  model_data <- thick_data_list[[index]]
  model_obj <- thick_model_list[[index]]
  
  centiles_plot(
    model_obj,
    model_data,
    xcol = substitute(interview_age),
    ycol = region_var,
    cent = centiles_to_plot,
    race = race4,
    sex = sex4,
    ylims = y_limits,
    region = region_label
  )
  
})
```


# Cortical Surface Area

## {.toolbar}

```{r}
#| title: "Select Options"
#| layout-nrow: 2
#| layout-ncol: 1
#| label: area-global-input

# select y variable
selectInput(
  "area_var",
  "Select area of brain to model cortical surface area: ",
  area_vars,
  selected = c("whole brain ")
  )

# centile input boxes
checkboxGroupInput(
  "centiles_area",
  "Select Centiles to Include in Plot",
  c(0.4, 2, 2.5, 10, 25, 50, 75, 90, 97.5, 98, 99.6),
  selected = c(2.5, 50, 97.5),
  inline = TRUE
  )

```


## Row

```{r}
#| content: card-toolbar
#| label: area-plot-1-input

# select race
selectInput(
  "race1",
  "Race",
  choices = race_levels,
  multiple = FALSE,
  selected = "All"
)

# select sex
selectInput(
  "sex1",
  "Sex",
  choices = c("Male", "Female"),
  multiple = FALSE,
  selected = "Female"
)
```

```{r}
#| title: "Plot 1"
#| label: area-plot-1

plotOutput("area_centile_plot_1")

```

```{r}
#| content: card-toolbar
#| label: area-plot-2-input

# select race
selectInput(
  "race2",
  "Race",
  choices = race_levels,
  multiple = FALSE,
  selected = "All"
)

# select sex
selectInput(
  "sex2",
  "Sex",
  choices = c("Male", "Female"),
  multiple = FALSE,
  selected = "Male"
)

```

```{r}
#| title: "Plot 2"
#| label: area-plot-2

plotOutput("area_centile_plot_2")
```

```{r}
#| label: area-calculate-and-plot-centiles
#| context: server

output$area_centile_plot_1 <- renderPlot({
  
  demog_brain_combos_area <- as.data.frame(demog_brain_combos_area)

  race1 <- input$race1[1]
  sex1 <- input$sex1[1]
  centiles_to_plot <- as.numeric(input$centiles_area)
  region_label <- input$area_var[1]
  region_var <- area_labels$var_name[which(area_labels$var_label == region_label)]
  
  index <- which(demog_brain_combos_area$sex == sex1 & demog_brain_combos_area$race_ethnicity == race1 & demog_brain_combos_area$brain_location == region_label)

  demog_brain_combos_area <- as.matrix(demog_brain_combos_area)

  y_limits <- c(as.numeric(demog_brain_combos_area[index, 5]),
                as.numeric(demog_brain_combos_area[index, 6]))
  
  model_data <- data_list[[index]]
  model_obj <- model_list[[index]]
  
  centiles_plot(
    model_obj,
    model_data,
    xcol = substitute(interview_age),
    ycol = region_var,
    cent = centiles_to_plot,
    race = race1,
    sex = sex1,
    ylims = y_limits,
    region = region_label
  )
  
})

output$area_centile_plot_2 <- renderPlot({
  
  demog_brain_combos_area <- as.data.frame(demog_brain_combos_area)
  race2 <- input$race2[1]
  sex2 <- input$sex2[1]
  centiles_to_plot <- as.numeric(input$centiles_area)
  region_label <- input$area_var[1]
  region_var <- area_labels$var_name[which(area_labels$var_label == region_label)]
  
  index <- which(
    demog_brain_combos_area$sex == sex2 &
      demog_brain_combos_area$race_ethnicity == race2 &
      demog_brain_combos_area$brain_location == region_label)
  
  y_limits <- c(as.numeric(demog_brain_combos_area[index, 5]),
                as.numeric(demog_brain_combos_area[index, 6]))
  
  model_data <- data_list[[index]]
  model_obj <- model_list[[index]]
  
  centiles_plot(
    model_obj,
    model_data,
    xcol = substitute(interview_age),
    ycol = region_var,
    cent = centiles_to_plot,
    race = race2,
    sex = sex2,
    ylims = y_limits,
    region = region_label
  )
  
})
```

